name: Basic Checks

on:
  merge_group:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target
        key: ${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - run: cargo fmt --check
    - run: cargo clippy

  check-py:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
      with:
        args: format --diff
    - uses: astral-sh/ruff-action@v3
      with:
        args: check tests

  test:
    runs-on: ubuntu-latest
    needs: ["check-rs", "check-py"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - run: cargo build --release
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.10'
        enable-cache: true
    - run: sudo apt install -y just

    - name: run tests
      run: uv run --with-requirements requirements.txt just test

    - run: uv cache prune --ci
